name: file_preview
description: A plug-in that supports flutter preview files
version: 2.0.0
homepage: https://github.com/gstory0404/file_preview

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FilePreviewPlugin